[workspace]
members = [
  "iceberg-rust-spec",
  "iceberg-rust",
  "datafusion_iceberg",
  "datafusion-iceberg-sql",
  "iceberg-sql-catalog",
  "iceberg-rest-catalog",
]

resolver = "2"

[workspace.dependencies]
object_store = { version = "0.9", features = ["aws", "gcp"] }
serde = "^1.0"
serde_derive = "^1.0"
serde_json = "^1.0"
futures = "0.3.30"
async-trait = "0.1"
chrono = { version = "0.4", default-features = false, features = ["serde"] }
arrow = "51.0.0"
arrow-schema = { version = "51.0.0", features = ["serde"]}
datafusion = "38.0.0"
datafusion-sql = "38.0.0"
datafusion-expr = "38.0.0"
datafusion-common = "38.0.0"
parquet = { version = "51.0.0", features = ["async", "object_store"] }
sqlparser = { version = "0.45.0", features = ["visitor"] }
thiserror = "1.0"
url = "^2.2"
uuid = { version = "1.3.2", features = ["serde", "v4"] }
itertools = "0.10.5"
derive-getters = "0.3.0"
tracing = "0.1"
tracing-futures = "0.2"

