[workspace]
members = [
  "iceberg-rust-spec",
  "iceberg-rust",
  "datafusion_iceberg",
  "datafusion-iceberg-sql",
  "iceberg-sql-catalog",
  "iceberg-rest-catalog",
  "iceberg-file-catalog",
  "iceberg-glue-catalog",
]

resolver = "2"

[workspace.dependencies]
apache-avro = "0.16.0"
object_store = { version = "0.11.0", features = ["aws", "gcp"] }
serde = "^1.0"
serde_derive = "^1.0"
serde_json = "^1.0"
futures = "0.3.30"
async-trait = "0.1"
chrono = { version = "0.4", default-features = false, features = ["serde", "clock"] }
arrow = "53.2.0"
arrow-schema = "53.2.0"
datafusion = { git = "https://github.com/dhruvils414/query-rust", branch = "upgrade" }
datafusion-sql = { git = "https://github.com/dhruvils414/query-rust", branch = "upgrade" }
datafusion-expr = { git = "https://github.com/dhruvils414/query-rust", branch = "upgrade" }
datafusion-common = { git = "https://github.com/dhruvils414/query-rust", branch = "upgrade" }
datafusion-execution = { git = "https://github.com/dhruvils414/query-rust", branch = "upgrade" }
datafusion-functions = {git = "https://github.com/dhruvils414/query-rust", branch = "upgrade", features = ["crypto_expressions"] }
datafusion-functions-aggregate = { git = "https://github.com/dhruvils414/query-rust", branch = "upgrade" }
parquet = { version = "53.2.0", features = ["async", "object_store"] }
sqlparser = { version = "0.51.0", features = ["visitor"] }
thiserror = "1.0"
url = "^2.2"
uuid = { version = "1.3.2", features = ["serde", "v4"] }
itertools = "0.10.5"
derive-getters = "0.3.0"
tracing = "0.1"
tracing-futures = "0.2"
