[package]
name = "datafusion_iceberg"
version = "0.3.0"
edition = "2021"

description = "Apache Iceberg integration for Datafusion"

license = "Apache-2.0"

repository = "https://github.com/JanKaul/iceberg-rust"

[dependencies]
futures = { workspace = true }
url = { workspace = true }
serde_json = { workspace = true }
async-trait = { workspace = true }
datafusion = { workspace = true }
datafusion-expr = { workspace = true }
datafusion-proto = {workspace = true}
chrono = { workspace = true }
object_store = { workspace = true }
iceberg-rust = { path = "../iceberg-rust", version = "0.3.0" }
iceberg-rust-spec = { path = "../iceberg-rust-spec", version = "0.3.0" }
iceberg-sql-catalog = { path = "../iceberg-sql-catalog" }
itertools = { workspace = true }
dashmap = "5.4.0"
uuid = { workspace = true }
thiserror = { workspace = true }
tokio = { version = "1.0", features = ["sync","rt-multi-thread"] }
lazy_static = "1.5.0"
prost = "0.12.6"
datafusion-common = { workspace = true }

[dev-dependencies]
tokio = "1"
iceberg-sql-catalog = { path = "../iceberg-sql-catalog" }

